basic_webhook:
  name: Basic Webhook
  description: Service Provider to use Webhooks
  fields:
    webhook:
      name: Webhook
      description: Webhook url
      required: true
      selector:
        text:
    json:
      name: Json Data
      description: Json Data To Send
      required: true
content_webhook:
  name: Content Webhook
  description: Service Provider to use Webhooks with content
  fields:
    webhook:
      name: Webhook
      description: Webhook url
      required: true
      selector:
        text:
    content:
      name: Content 
      description: Message Content
      selector:
        text:
    json:
      name: Json Data
      description: Json Data To Send  